[package]
name = "gpui-ohos-example"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lib]
name = "gpui_ohos_example"
crate-type = ["cdylib"]
doctest = false
test = false

[dependencies]
gpui-ohos = { path = "..", default-features = false }
log = "0.4"
napi-derive-ohos = "=1.2.0"
napi-ohos = "=1.2.0"
openharmony-ability = { git = "https://github.com/richerfu/openharmony-ability.git", rev = "ea5d815025d3cf349176536d22da2bb1a5880af6" }
openharmony-ability-derive = { git = "https://github.com/richerfu/openharmony-ability.git", rev = "ea5d815025d3cf349176536d22da2bb1a5880af6" }

[features]
default = ["gles"]
gles = ["gpui-ohos/gles"]
vulkan = ["gpui-ohos/vulkan"]

[build-dependencies]
napi-build-ohos = "=1.2.0"

[workspace]
resolver = "2"
